const byId=id=>document.getElementById(id);
let tokens=fresh(),selected=198,count=1,operation='replace',undoStack=[],redoStack=[],message='まだ編集していません。';
const dnaString=()=>tokens.map(t=>t.base).join('');
const cleanInput=()=>byId('letters').value.toUpperCase().replace(/\s/g,'');
function snapshot(){return {tokens:tokens.map(t=>({...t})),selected,count,message};}
function restore(s){tokens=s.tokens.map(t=>({...t}));selected=s.selected;count=s.count;message=s.message;render();}
function remember(){undoStack.push(snapshot());redoStack=[];}
function selectPosition(n){selected=Math.max(0,Math.min(tokens.length-1,Math.floor(n)));if(count===3)selected-=selected%3;render();}
function setOperation(op){operation=op;renderControls();}
function renderControls(){document.querySelectorAll('[data-count]').forEach(b=>b.setAttribute('aria-pressed',Number(b.dataset.count)===count));document.querySelectorAll('[data-op]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.op===operation));byId('input-area').hidden=operation==='cut';byId('input-label').textContent=operation==='insert'?'選んだ文字の直前に入れるDNA（1〜60文字）':'新しい文字';const old=dnaString().slice(selected,selected+count),input=cleanInput();byId('selection-label').textContent=`${selected+1}${old.length>1?'〜'+(selected+old.length):''}番目「${old}」`;byId('edit-preview').textContent=operation==='cut'?`「${old}」を切り取り、左右のDNAをつなぎます。`:operation==='insert'?`${selected+1}番目の直前に「${input||'…'}」を挿入します。`:`「${old}」を「${input||'…'}」に書き換えます。`;byId('undo').disabled=undoStack.length===0;byId('redo').disabled=redoStack.length===0;}
function visual(id,result){const svg=byId(id),unknown=['unknown','short'].includes(result.kind);let html='';const n=result.start?Math.min(36,Math.max(0,Math.round(result.protein.length/REF_PROTEIN.length*36))):0;for(let i=0;i<36;i++){const x=35+(i%6)*26,y=18+Math.floor(i/6)*23;html+=`<circle cx="${x}" cy="${y}" r="8" fill="${i<n?result.color:'none'}" stroke="${i<n?result.color:'#42433d'}" opacity="${unknown?.55:1}"/>`;}if(unknown)html+='<circle cx="100" cy="75" r="22" fill="#0e100f"/><text x="100" y="86" text-anchor="middle" fill="#fffce1" font-size="32">?</text>';const changed=svg.innerHTML!==html;svg.innerHTML=html;svg.setAttribute('aria-label',result.kind==='green'?'緑色蛍光タンパク質の模式図':result.kind==='blue'?'青色への変化を示す研究参考図':'蛍光が不明、または翻訳できないタンパク質の模式図');if(changed&&id==='edited-visual'&&svg.animate&&!window.matchMedia('(prefers-reduced-motion: reduce)').matches)svg.animate([{opacity:.4},{opacity:1}],{duration:350});}
function render(){const dna=dnaString(),r=analyze(dna),page=Math.floor(selected/12)*12;byId('length').textContent=dna.length;byId('position').max=dna.length;byId('position').value=selected+1;byId('overview').max=dna.length;byId('overview').value=selected+1;byId('prev').disabled=page===0;byId('next').disabled=page+12>=dna.length;
let html='';for(let start=page;start<Math.min(page+12,dna.length);start+=3){const chunk=dna.slice(start,start+3),aa=CODE[chunk]||'?';html+=`<div class="codon"><div class="codon-location">${start+1}–${Math.min(start+3,dna.length)}番目</div><div class="bases">`;for(let i=start;i<Math.min(start+3,dna.length);i++){const t=tokens[i],old=t.origin===null?null:REFERENCE[t.origin],edited=old!==t.base,on=i>=selected&&i<selected+count;html+=`<button class="base ${on?'selected':''} ${edited?'edited':''}" data-base="${t.base}" data-index="${i}" aria-pressed="${on}" aria-label="${i+1}番目 ${t.base}${edited?' 編集済み':''}">${t.base}<small>${old===null?'挿入':edited?'元 '+old:'　'}</small></button>`;}html+=`</div><div class="codon-aa">→ ${AA_NAMES[aa]}${r.stop>=0&&start/3>r.stop?'（終了後）':''}</div></div>`;}byId('dna').innerHTML=html;
visual('original-visual',analyze(REFERENCE));visual('edited-visual',r);byId('phenotype').textContent={green:'緑の蛍光',blue:'青への変化例',short:'蛍光は不明',unknown:'蛍光は不明',start:'翻訳できない'}[r.kind];byId('phenotype').style.color=r.color;byId('protein-length').textContent=`材料 ${r.protein.length}個${r.stop<0&&r.start?'・終了なし':''}`;byId('result-badge').textContent=r.kind==='blue'?'色は研究を参考に表示':'DNAから読み取り計算';byId('conclusion-title').textContent=r.title;byId('conclusion-title').style.color=r.color;byId('conclusion-detail').textContent=r.detail;
const index=Math.floor(selected/3),ref=translate(REFERENCE),current=r.codons[index],prev=ref.codons[index];byId('translation').innerHTML=`<div class="translation-row"><span>編集前<small>${index+1}組目</small></span><div><code>${prev?.codon||'—'}</code><small>${prev?AA_NAMES[prev.aa]:'元の配列の範囲外'}</small></div></div><div class="translation-row"><span>編集後<small>同じ位置</small></span><div><code>${current?.codon||'—'}</code><small>${!r.start?'先頭の開始合図なし → 翻訳しない':r.stop>=0&&index>r.stop?'すでに終了しているため、この部分は翻訳しない':AA_NAMES[current?.aa||'?']}</small></div></div>`;
const diff=dna.length-REFERENCE.length;byId('frame-note').textContent=r.shift?`DNAの全長差が${diff>0?'+':''}${diff}文字。3の倍数でない挿入・削除は、それ以降の読み分けをずらします。`:`DNAの全長差は${diff>0?'+':''}${diff}文字。材料の変化は、編集後の配列を3文字ずつ読み直した結果です。`;
let changed=0;byId('beads').innerHTML=[...r.protein].map((aa,i)=>{const isChanged=aa!==REF_PROTEIN[i];if(isChanged)changed++;return `<i class="${isChanged?'changed':''}"></i>`;}).join('');byId('protein-summary').textContent=`${changed}か所で材料が異なる`;byId('edit-status').textContent=message;byId('error').textContent='';renderControls();}
byId('dna').onclick=e=>{const b=e.target.closest('[data-index]');if(b)selectPosition(Number(b.dataset.index));};
byId('dna').onkeydown=e=>{const b=e.target.closest('[data-index]');if(!b||!['ArrowRight','ArrowLeft'].includes(e.key))return;e.preventDefault();selectPosition(selected+(e.key==='ArrowRight'?1:-1));document.querySelector(`[data-index="${selected}"]`)?.focus();};
document.querySelectorAll('[data-count]').forEach(b=>b.onclick=()=>{count=Number(b.dataset.count);if(count===3)selected-=selected%3;byId('letters').value=dnaString().slice(selected,selected+count);render();});
document.querySelectorAll('[data-op]').forEach(b=>b.onclick=()=>setOperation(b.dataset.op));
document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>{const value=b.dataset.jump;if(value==='end')selectPosition(tokens.length-3);else{const n=Number(value),pos=tokens.findIndex(t=>t.origin===n);selectPosition(pos<0?Math.min(n,tokens.length-1):pos);}});
byId('prev').onclick=()=>selectPosition(Math.max(0,Math.floor(selected/12)*12-12));byId('next').onclick=()=>selectPosition(Math.min(tokens.length-1,Math.floor(selected/12)*12+12));byId('overview').oninput=e=>selectPosition(Number(e.target.value)-1);byId('position').onchange=e=>{const n=Number(e.target.value);if(!Number.isInteger(n)||n<1||n>tokens.length){byId('error').textContent=`位置は1〜${tokens.length}で指定してください。`;return;}selectPosition(n-1);};
byId('letters').oninput=()=>{byId('error').textContent='';renderControls();};document.querySelectorAll('[data-letter]').forEach(b=>b.onclick=()=>{const input=byId('letters');input.value=operation==='replace'&&cleanInput().length>=Math.min(count,tokens.length-selected)?b.dataset.letter:(input.value+b.dataset.letter).slice(0,60);renderControls();});
byId('apply').onclick=()=>{try{const old=dnaString().slice(selected,selected+count),input=cleanInput(),next=editDNA(tokens,selected,count,operation,input);if(next.map(t=>t.base).join('')===dnaString()){byId('error').textContent='同じ文字です。別の文字に変えてみよう。';return;}remember();const position=selected+1;tokens=next;selected=Math.min(selected,tokens.length-1);message=operation==='cut'?`${position}番目から「${old}」を切り取りました。`:operation==='insert'?`${position}番目の直前に「${input}」を入れました。`:`${position}番目の「${old}」を「${input}」に書き換えました。`;render();byId('mobile-result').textContent='結果が変わった ↓';}catch(error){byId('error').textContent=error.message;}};
byId('undo').onclick=()=>{if(!undoStack.length)return;redoStack.push(snapshot());restore(undoStack.pop());};byId('redo').onclick=()=>{if(!redoStack.length)return;undoStack.push(snapshot());restore(redoStack.pop());};byId('reset').onclick=()=>{if(dnaString()!==REFERENCE)remember();tokens=fresh();selected=198;count=1;operation='replace';byId('letters').value='C';message='最初のDNAに戻しました。';render();};
document.querySelectorAll('[data-hint]').forEach(b=>b.onclick=()=>{if(dnaString()!==REFERENCE){byId('hint-text').textContent='このヒントは元のDNA用です。「最初のDNAに戻す」で準備してください。';return;}const hints={blue:[198,'replace','C','光の中心のTをCに書き換えて、材料を変えてみよう。'],stop:[200,'replace','A','TACをTAAに変えて、「終了」の合図を作ってみよう。'],silent:[17,'replace','A','GAGをGAAに変えてみよう。DNAが変わっても材料は変わる？'],shift:[198,'cut','','1文字を抜いて、その先の3文字区切りを比べよう。']},h=hints[b.dataset.hint];selected=h[0];count=1;operation=h[1];byId('letters').value=h[2];byId('hint-text').textContent=h[3];render();byId('dna').scrollIntoView({block:'center',behavior:'auto'});});
byId('mobile-result').onclick=()=>{const result=byId('result'),atResult=result.getBoundingClientRect().top<window.innerHeight*.5&&result.getBoundingClientRect().bottom>0;if(atResult){byId('editor-title').scrollIntoView({block:'start',behavior:'auto'});byId('mobile-result').textContent='結果を見る ↓';}else{result.scrollIntoView({block:'start',behavior:'auto'});result.focus({preventScroll:true});byId('mobile-result').textContent='DNAに戻る ↑';}};
render();
