// EGFP CDS published by Ambryon. Protein checked against FPbase R9NL8.
const REFERENCE='ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCCTGGTCGAGCTGGACGGCGACGTAAACGGCCACAAGTTCAGCGTGTCCGGCGAGGGCGAGGGCGATGCCACCTACGGCAAGCTGACCCTGAAGTTCATCTGCACCACCGGCAAGCTGCCCGTGCCCTGGCCCACCCTCGTGACCACCCTGACCTACGGCGTGCAGTGCTTCAGCCGCTACCCCGACCACATGAAGCAGCACGACTTCTTCAAGTCCGCCATGCCCGAAGGCTACGTCCAGGAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCGCCGAGGTGAAGTTCGAGGGCGACACCCTGGTGAACCGCATCGAGCTGAAGGGCATCGACTTCAAGGAGGACGGCAACATCCTGGGGCACAAGCTGGAGTACAACTACAACAGCCACAACGTCTATATCATGGCCGACAAGCAGAAGAACGGCATCAAGGTGAACTTCAAGATCCGCCACAACATCGAGGACGGCAGCGTGCAGCTCGCCGACCACTACCAGCAGAACACCCCCATCGGCGACGGCCCCGTGCTGCTGCCCGACAACCACTACCTGAGCACCCAGTCCGCCCTGAGCAAAGACCCCAACGAGAAGCGCGATCACATGGTCCTGCTGGAGTTCGTGACCGCCGCCGGGATCACTCTCGGCATGGACGAGCTGTACAAGTAA';
const AA_NAMES={A:'アラニン',R:'アルギニン',N:'アスパラギン',D:'アスパラギン酸',C:'システイン',Q:'グルタミン',E:'グルタミン酸',G:'グリシン',H:'ヒスチジン',I:'イソロイシン',L:'ロイシン',K:'リシン',M:'メチオニン',F:'フェニルアラニン',P:'プロリン',S:'セリン',T:'スレオニン',W:'トリプトファン',Y:'チロシン',V:'バリン','*':'終了','?':'3文字に足りない'};
const CODE={};let ci=0;for(const a of 'TCAG')for(const b of 'TCAG')for(const c of 'TCAG')CODE[a+b+c]='FFLLSSSSYY**CC*WLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG'[ci++];
function translate(dna){const codons=[];let protein='',stop=-1;const start=dna.startsWith('ATG');for(let i=0;i<dna.length;i+=3){const codon=dna.slice(i,i+3),aa=CODE[codon]||'?';codons.push({codon,aa});if(start&&stop<0){if(aa==='*')stop=i/3;else if(aa!=='?')protein+=aa;}}return {codons,protein,stop,start,remainder:dna.length%3};}
const REF_PROTEIN=translate(REFERENCE).protein;
function fresh(){return [...REFERENCE].map((base,origin)=>({base,origin}));}
function editDNA(tokens,start,count,operation,input){if(!Number.isInteger(start)||start<0||start>=tokens.length)throw Error('編集する場所を選んでください。');if(![1,3].includes(count))throw Error('1文字か3文字を選んでください。');const n=Math.min(count,tokens.length-start),text=input.toUpperCase().replace(/\s/g,'');if(operation!=='cut'&&(!/^[ACGT]+$/.test(text)||text.length>60))throw Error('A・T・G・Cを1〜60文字で入力してください。');if(operation==='replace'&&text.length!==n)throw Error(`書き換える文字を${n}文字入力してください。`);if(operation==='cut'&&tokens.length<=n)throw Error('DNAをすべて消すことはできません。');if(operation==='insert'&&tokens.length+text.length>1440)throw Error('この実験ではDNAを1,440文字まで編集できます。');const next=tokens.map(t=>({...t}));if(operation==='cut')next.splice(start,n);else if(operation==='replace')next.splice(start,n,...[...text].map((base,i)=>({base,origin:tokens[start+i].origin})));else if(operation==='insert')next.splice(start,0,...[...text].map(base=>({base,origin:null})));else throw Error('操作を選んでください。');return next;}
function analyze(dna){const t=translate(dna),same=t.protein===REF_PROTEIN;let kind,title,detail,color;
if(!t.start){kind='start';title='最初の「読み始める」がなくなった。';detail='先頭のATGが変わっています。このモデルでは先頭のATGからのみ翻訳するため、タンパク質は作られません。別の位置から始まる可能性は計算していません。';color='#7c7c6f';}
else if(same&&t.stop===REF_PROTEIN.length){kind='green';title=dna===REFERENCE?'元のDNAは、緑の蛍光タンパク質になる。':'DNAは変わった。でも材料の並びは同じ。';detail=dna===REFERENCE?'光るタンパク質「EGFP」の実在するDNAです。下の文字を選んで、編集してみよう。':'違う3文字でも、同じアミノ酸を指定することがあります。材料の並びは元と同じです。作られる量まで同じとは限りません。';color='#abff84';}
else if(t.protein===REF_PROTEIN.slice(0,66)+'H'+REF_PROTEIN.slice(67)&&t.stop===REF_PROTEIN.length){kind='blue';title='光の中心の材料が変わった。';detail='チロシン（Y）がヒスチジン（H）に変化。GFPで青色への変化が報告されている置換に相当します。青は研究を参考にした模式表示で、この配列の実測予測ではありません。';color='#00bae2';}
else if(t.stop>=0&&t.protein.length<REF_PROTEIN.length){kind='short';title=`途中で終了。材料が${t.protein.length}個で止まった。`;detail=`${t.stop+1}組目が「終了」の合図です。その先のDNAが残っていても、そこで材料をつなぐのが止まります。蛍光が保たれるかは計算だけでは断定できません。`;color='#ff8709';}
else{kind='unknown';title='材料の並びが変わった。光り方はまだ不明。';detail=t.stop<0?'この範囲には終了の合図がありません。配列の外側は未計算です。形や蛍光は、この読み取り計算だけでは予測できません。':'タンパク質の材料が変わりました。新しい形や色を決めつけず、未知の結果として表示します。';color='#9d95ff';}
return {...t,kind,title,detail,color,shift:(dna.length-REFERENCE.length)%3!==0,same};}
if(typeof module!=='undefined')module.exports={REFERENCE,REF_PROTEIN,CODE,translate,fresh,editDNA,analyze};
